# Generated by Django 4.2.7 on 2025-12-07 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penguin_app', '0002_user_verification_token_expires_journalentry_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['user', '-date', '-created_at'], name='journal_user_date_idx'),
        ),
    ]
