# Generated by Django 4.2.7 on 2025-12-01 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penguin_app', '0003_calendarevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalendarEvent',
        ),
    ]
