# Generated by Django 4.2.7 on 2025-12-08 04:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('penguin_app', '0004_alter_journalentry_user_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
