# Generated by Django 4.2.7 on 2025-12-08 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('penguin_app', '0005_alter_calendarevent_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Short name of the habit (e.g. 'Drink Water')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description of the habit.')),
                ('category', models.CharField(blank=True, default='General', help_text='Category label used for grouping and icons.', max_length=50)),
                ('emoji', models.CharField(blank=True, help_text='Optional emoji representation for the habit.', max_length=10)),
                ('color', models.CharField(blank=True, help_text='Optional color name or hex code for UI styling.', max_length=20)),
                ('icon', models.CharField(blank=True, help_text="Icon name for Flutter IconData (e.g. 'water_drop', 'fitness_center').", max_length=50)),
                ('daily_goal', models.PositiveIntegerField(default=1, help_text='Target units per day (e.g. 8 cups of water).')),
                ('unit', models.CharField(blank=True, default='times', help_text="Unit of measurement (e.g. 'glasses', 'steps', 'minutes').", max_length=20)),
                ('today_count', models.PositiveIntegerField(default=0, help_text='Progress for the current day.')),
                ('schedule', models.CharField(blank=True, default='DAILY', help_text='Simple frequency label (e.g. DAILY, WEEKDAYS).', max_length=32)),
                ('last_completed', models.DateField(blank=True, help_text='Date when the habit was last marked complete.', null=True)),
                ('reward', models.PositiveIntegerField(default=5, help_text='Fish coins earned when completing this habit.')),
                ('streak', models.PositiveIntegerField(default=0, help_text='Current consecutive days streak.')),
                ('week_progress', models.JSONField(blank=True, default=list, help_text='Array of 7 booleans representing completion for each day of the week.')),
                ('is_active', models.BooleanField(default=True, help_text='If false, this habit should not appear in active lists.')),
                ('is_archived', models.BooleanField(default=False, help_text='If true, the habit is archived/hidden instead of deleted.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(auto_now_add=True, help_text='Date when the habit was first created/started.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'habits',
                'ordering': ('created_at',),
            },
        ),
    ]
