# Generated by Django 4.2.7 on 2025-12-01 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penguin_app', '0005_calendarevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='updated_at',
        ),
    ]
