// Model representing a calendar event
// Each event has a title, description, and start/end times
class CalendarEvent {
  final String id; // UUID from backend
  final String title; // Event name
  final String description; // Event details
  final DateTime startTime; // When the event starts
  final DateTime endTime; // When the event ends

  CalendarEvent({
    required this.id,
    required this.title,
    required this.description,
    required this.startTime,
    required this.endTime,
  });

  // Create a CalendarEvent from JSON data received from the backend
  factory CalendarEvent.fromJson(Map<String, dynamic> json) {
    return CalendarEvent(
      id: json['id'] as String,
      title: json['title'] as String,
      description: json['description'] as String,
      startTime: DateTime.parse(json['start_time'] as String),
      endTime: DateTime.parse(json['end_time'] as String),
    );
  }

  // Convert CalendarEvent to JSON format for sending to backend
  // Note: ID is not included as it's generated by the backend
  Map<String, dynamic> toJson() {
    return {
      'title': title,
      'description': description,
      'start_time': startTime.toIso8601String(),
      'end_time': endTime.toIso8601String(),
    };
  }
}